version: '3.9'

services:
  pg:
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../update
      dockerfile: ../../update/Dockerfile
    environment:
      POSTGRES_URL: postgresql://app:example@pg:5432/app
      PORT: 3000
    env_file:
      - ../../update/.env
    ports:
      - "3000:3000"
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pg-data:
