const SECOND = 1000;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;

export const CacheTTL = {
   ONE_MINUTE: MINUTE,
   TWO_MINUTE: 2 * MINUTE,
   THREE_MINUTE: 3 * MINUTE,
   FIVE_MINUTE: 5 * MINUTE,
   TEN_MINUTE: 10 * MINUTE,
   FIFTEEN_MINUTE: 15 * MINUTE,
   TWENTY_MINUTE: 20 * MINUTE,

   ONE_HOUR: HOUR,
   TWO_HOUR: 2 * HOUR,
   THREE_HOUR: 3 * HOUR,
   FIVE_HOUR: 5 * HOUR,
};
