name: Node.js version matrix tests

on:
   push:
      branches: [main]
      paths:
         - 'microservices/**'
         - 'src/**'
         - 'package.json'
         - 'package-lock.json'
         - 'test/**'
   pull_request:
      paths:
         - 'microservices/**'
         - 'src/**'
         - 'package.json'
         - 'package-lock.json'
         - 'test/**'

jobs:
   node-matrix:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [18, 20, 24]
      name: Node ${{ matrix.node-version }} - unit tests
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - name: Cache node modules
           uses: actions/cache@v4
           with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
         - name: Install dependencies
           run: npm install --legacy-peer-deps
         - name: Build app
           run: npm run build
         - name: Run unit tests
           run: npm run test:unit
